name: CI / Publish

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  tests:
    name: 🧪 Tests
    uses: ./.github/workflows/tests.yml

  publish:
    name: 📦 Publish
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v4

      - name: 🔨 Setup
        uses: ./.github/workflows/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📦 Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
